wandb_version: 1

batch_size:
  desc: null
  value: 128
layer_num:
  desc: null
  value: 5
layer_size:
  desc: null
  value: 48
learning_rate:
  desc: null
  value: 0.003584113769237588
_wandb:
  desc: null
  value:
    python_version: 3.7.16
    cli_version: 0.16.1
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1706624641.464412
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      2:
      - 1
      - 5
      - 53
      - 55
      3:
      - 2
      - 23
      - 37
      4: 3.7.16
      5: 0.16.1
      8:
      - 5
      13: linux-x86_64
